server:
  port: 9527
spring:
  application:
    name: PINXIXI-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone:http://localhost:7001/eureka
  instance:
    instance-id:pinxixi-zuul-gateway-9527.com #为当前服务器添加实例的标识
    prefix:"/services"#这是所有路径的前缀
    routes:
      plat:
        path:/plat/**
        service-id:pinxixi-plat